apiVersion: v1
kind: Service
metadata:
  name: healthprobe-app-svc
  namespace: healthprobe-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: healthprobe-app
