apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthprobe-app-deployment
  namespace: healthprobe-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: healthprobe-app
  template:
    metadata:
      labels:
        app: healthprobe-app
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      # https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
      # lifecycle:
      #   preStop:
      #     exec:
      #       command: ["/bin/sh", "-c", "sleep 15"]
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: jannemattila/k8s-probe-demo:1.0.15
          name: healthprobe-app
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 150Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/healthcheck/startup
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/healthcheck/liveness
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/healthcheck/readiness
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: webhook
              value: http://echo-app-svc.echo-app.svc.cluster.local/api/echo
            - name: livenessCheck
              value: "true"
            - name: readinessCheck
              value: "true"
            - name: delayStartup
              value: "0"
            - name: delayShutdown
              value: "10"
