apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthprobe-app-deployment
  namespace: healthprobe-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: healthprobe-app
  template:
    metadata:
      labels:
        app: healthprobe-app
    spec:
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: jannemattila/k8s-probe-demo:1.0.14
          name: healthprobe-app
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          startupProbe:
            httpGet:
              path: /api/HealthCheck/Startup
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/HealthCheck/Liveness
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/HealthCheck/Readiness
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: webhook
              value: http://echo-app-svc.echo-app.svc.cluster.local/api/echo
            - name: livenessCheck
              value: "true"
            - name: readinessCheck
              value: "true"
