apiVersion: v1
kind: Namespace
metadata:
  name: storage-app-zrs
---
apiVersion: v1
kind: Service
metadata:
  name: storage-app-zrs-svc
  namespace: storage-app-zrs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: storage-app-zrs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-app-zrs-deployment
  namespace: storage-app-zrs
spec:
  serviceName: storage-app-zrs-svc
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: storage-app-zrs
  template:
    metadata:
      labels:
        app: storage-app-zrs
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.azure.com/mode: user
      terminationGracePeriodSeconds: 10
      containers:
        - image: jannemattila/webapp-update:1.0.15
          name: storage-app-zrs
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: premiumdisk
              mountPath: /mnt/premiumdisk
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: premiumdisk
          persistentVolumeClaim:
            claimName: premiumdisk-pvc
  volumeClaimTemplates:
    - metadata:
        name: premiumdisk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi

