apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-app-deployment
  namespace: yarp-app
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: yarp-app
  template:
    metadata:
      labels:
        app: yarp-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        # kubernetes.azure.com/mode: user
      terminationGracePeriodSeconds: 30
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "sleep 15"]
      containers:
        - image: jannemattila/yarp-aad-le:1.0.12
          name: yarp-app
          # env:
          #   - name: ASPNETCORE_URLS
          #     value: http://*:8080
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
