apiVersion: v1
kind: Service
metadata:
  name: storage-app-svc
  namespace: storage-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: storage-app
