apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-app-deployment
  namespace: storage-app
spec:
  serviceName: storage-app-svc
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: storage-app
  template:
    metadata:
      labels:
        app: storage-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 10
      containers:
        - image: jannemattila/webapp-fs-tester:1.1.13
          name: storage-app
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            # - name: empty
            #   mountPath: /mnt/empty
            # - name: hostpath
            #   mountPath: /mnt/hostpath
            # - name: nfs
            #   mountPath: /mnt/nfs
            # - name: smb
            #   mountPath: /mnt/smb
            - name: premiumdisk
              mountPath: /mnt/premiumdisk
            # - name: ultradisk
            #   mountPath: /mnt/ultradisk
            # - name: netapp-nfs
            #   mountPath: /mnt/netapp-nfs
      # volumes:
      # - name: empty
      #   emptyDir: {}
      # - name: hostpath
      #   hostPath:
      #     path: /mnt
      # - name: nfs
      #   persistentVolumeClaim:
      #     claimName: nfs-pvc
      # - name: smb
      #   persistentVolumeClaim:
      #     claimName: smb-pvc
      # - name: premiumdisk
      #   persistentVolumeClaim:
      #     claimName: premiumdisk-pvc
      # - name: ultradisk
      #   persistentVolumeClaim:
      #     claimName: ultradisk-pvc
      # - name: netapp-nfs
      #   persistentVolumeClaim:
      #     claimName: netapp-nfs-pvc
  volumeClaimTemplates:
    - metadata:
        name: premiumdisk
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-csi-premium-sc
        resources:
          requests:
            storage: 5Gi
