apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: premiumdisk-pvc
  namespace: storage-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-premium-sc
  resources:
    requests:
      storage: 5Gi
