apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-app-deployment
  namespace: storage-app
spec:
  serviceName: storage-app-svc
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: storage-app
  template:
    metadata:
      labels:
        app: storage-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 10
      containers:
        - image: jannemattila/webapp-fs-tester:1.1.13
          name: storage-app
          # https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/fail-to-mount-azure-disk-volume#cause-changing-ownership-and-permissions-for-large-volume-takes-much-time
          # securityContext:
          #   runAsUser: 1000
          #   runAsGroup: 3000
          #   fsGroup: 2000
          #   fsGroupChangePolicy: "OnRootMismatch"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            # - name: empty
            #   mountPath: /mnt/empty
            # - name: hostpath
            #   mountPath: /mnt/hostpath
            - name: nfs
              mountPath: /mnt/nfs
            - name: premiumdisk
              mountPath: /mnt/premiumdisk
      volumes:
        # - name: empty
        #   emptyDir: {}
        # - name: hostpath
        #   hostPath:
        #     path: /mnt
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
        - name: premiumdisk
          persistentVolumeClaim:
            claimName: premiumdisk-pvc
  volumeClaimTemplates:
    - metadata:
        name: premiumdisk
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-csi-premium-sc
        resources:
          requests:
            storage: 5Gi
