apiVersion: v1
kind: Service
metadata:
  name: network-app-internal-svc
  namespace: network-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: network-app
