apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-app-deployment
  namespace: network-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-app
  template:
    metadata:
      labels:
        app: network-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        # kubernetes.azure.com/mode: user
      # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
      # dnsPolicy: ClusterFirst
      # dnsConfig:
      #   nameservers:
      #     - 192.0.2.1
      #   searches:
      #     - ns1.svc.cluster-domain.example
      #     - my.dns.search.suffix
      #   options:
      #     - name: ndots
      #       value: "2"
      #     - name: edns0
      containers:
        - image: jannemattila/webapp-network-tester:1.0.65
          name: network-app
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: DB_PORT
              value: "1234"
            - name: DB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: network-app-configmap
                  key: DB_SERVER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: network-app-secret
                  key: supersecret
          volumeMounts:
            - name: hostpath
              mountPath: /mnt/host
            - name: configmap
              mountPath: /mnt/config
      volumes:
        - name: hostpath
          hostPath:
            path: /
        - name: configmap
          configMap:
            name: network-app-configmap
            defaultMode: 0744
