apiVersion: v1
kind: Service
metadata:
  name: postgresql-app-svc
  namespace: postgresql-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: postgresql-app
