BEGIN;
CREATE TABLE IF NOT EXISTS public.customers (
  customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name text NOT NULL
);

INSERT INTO public.customers (customer_id, company_name)
VALUES
  (DEFAULT, 'Contoso'),
  (DEFAULT, 'Fabrikam'),
  (DEFAULT, 'Adventure Works'),
  (DEFAULT, 'Northwind Traders'),
  (DEFAULT, 'Tailspin Toys');
COMMIT;

\timing

INSERT INTO public.customers (customer_id, company_name)
VALUES (DEFAULT, 'company');

SELECT * FROM public.customers;

SELECT * FROM public.customers;
SELECT * FROM public.customers WHERE customer_id = 6;

UPDATE public.customers
SET company_name = gen_random_uuid()::text
WHERE customer_id = 6;

\q
