apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: placeholder-priority
value: -1
globalDefault: false
preemptionPolicy: Never
description: "This priority class is only used by placeholder workload."
