apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-app-deployment
  namespace: placeholder-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder-app
  template:
    metadata:
      labels:
        app: placeholder-app
    spec:
      priorityClassName: placeholder-priority
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: placeholder-app
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.azure.com/mode: user
        usage: tempworkloads
      tolerations:
        - key: "usage"
          operator: "Equal"
          value: "tempworkloads"
          effect: "NoSchedule"
      containers:
        - name: placeholder-app
          image: jannemattila/webapp-network-tester:1.0.75
          resources:
            requests:
              cpu: 6000m
              memory: 12Gi
            limits:
              cpu: 6000m
              memory: 12Gi
