# https://kubernetes.io/docs/concepts/services-networking/network-policies/
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: echo-app-network-policy
  namespace: echo-app
spec:
  podSelector:
    matchLabels:
      app: echo-app
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: network-app
