apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app-deployment
  namespace: echo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: jannemattila/echo:1.0.107
          name: echo-app
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
